package Example;

public class ArithmaticException 
{

	public static void main(String[] args) 
	{
		try
		{
			int x = 100;
		    int y = 0;
		    int result = x / y;
		    
		    System.out.println (" Result :  " + result );
		}
		catch ( Exception e )
		{
			System.out.println (" Arithmatic Exception " );
            
		}
		
		 System.out.println ("Continue Program " );
	
	}

}
